### PR TITLE
Restrict runtime Python<3.8

### PR DESCRIPTION
**Pull request by jpgill86**
Fixes conda-forge/pyqtgraph-feedstock#10

Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] <strike>Reset the build number to `0` (if the version changed)</strike> (N/A)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jpgill86** [comment]
@conda-forge-admin, please rerender

**Comment by jpgill86** [comment]
A (probably better) alternative to excluding Python 3.8: Add a patch to the recipe that applies the changes in pyqtgraph/pyqtgraph#980.

**Comment by marcelotrevisani** [comment]
I think it is better to exclude it for now, when they release a new version we can add Python 3.8 :)

**Comment by jpgill86** [comment]
That is fine with me, although there is [precedent](https://github.com/conda-forge/pyqtgraph-feedstock/pull/7) for applying patches in this project, and as far as I can tell, the release cycle for pyqtgraph is very, very long.

**Comment by jpgill86** [comment]
Because the pyqtgraph release cycle is so long (last released 3 years ago) and I haven't seen indications of a new release coming soon (the GitHub milestone for the next release has many open issues), I would suggest that patching the incompatibility would be better. I've opened a second pull request (#12) which implements this change. I'd prefer that PR accepted instead of this one, since it could mean I get to start using 3.8 now rather than never!

**Pull request closed without merging**
