### PR TITLE
Update for release candidate 0.11.0rc0

### PR DESCRIPTION
**Pull request by ksunden**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ksunden** [comment]
@astaric
@marcelotrevisani

We received a request for rthe latest release candidate over at pyqtgraph/pyqtgraph#1107

I was the one who did the release to pypi, if you'd like me to add myself as a maintainer here, willing to do so.

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Comment by marcelotrevisani** [comment]
> @astaric
> @marcelotrevisani
> 
> We received a request for rthe latest release candidate over at [pyqtgraph/pyqtgraph#1107](https://github.com/pyqtgraph/pyqtgraph/issues/1107)
> 
> I was the one who did the release to pypi, if you'd like me to add myself as a maintainer here, willing to do so.

Please, feel free to add yourself as a maintainer! :)

**Comment by marcelotrevisani** [comment]
@conda-forge-admin , please rerender

**Pull request merged**
