### PR TITLE
New build

### PR DESCRIPTION
**Pull request by jan-janssen**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jan-janssen** [comment]
@conda-forge-admin, please rerender

**Comment by jpgill86** [comment]
For @marcelotrevisani's understanding: I think @jan-janssen added these changes to meta.yaml based on the recommendation of [this page](https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl), following our conversation [here](https://github.com/conda-forge/staged-recipes/pull/10103).

Since #8 passed its tests, perhaps these changes won't be needed? I'll try out the new pyqtgraph once it's built and report back.

**Comment by marcelotrevisani** [comment]
> For @marcelotrevisani's understanding: I think @jan-janssen added these changes to meta.yaml based on the recommendation of [this page](https://conda-forge.org/docs/maintainer/knowledge_base.html#libgl), following our conversation [here](https://github.com/conda-forge/staged-recipes/pull/10103).
> 
> Since #8 passed its tests, perhaps these changes won't be needed? I'll try out the new pyqtgraph once it's built and report back.

I add the ``recipe/yum_requirements.txt`` so this recipe can continue to be ``noarch``. The problem was regarding those ``libgl`` and ``libx11`` which are responsible to communicate with the graphics stuff.

**Comment by jpgill86** [comment]
> I'll try out the new pyqtgraph once it's built and report back.

It appears to be working!

**Pull request closed without merging**
